apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-api
subjects:
- kind: ServiceAccount
  name: cluster-api
