apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: karpenter-operator
  namespace: HCP_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: karpenter-operator
subjects:
- kind: ServiceAccount
  name: karpenter-operator
