apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capi-provider-controller-manager
      control-plane: capi-provider-controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capi-provider-controller-manager
        control-plane: capi-provider-controller-manager
    spec: {}
