apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capi-provider
rules:
- apiGroups:
  - ""
  resources:
  - events
  - secrets
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  - controlplane.cluster.x-k8s.io
  - infrastructure.cluster.x-k8s.io
  - machines.cluster.x-k8s.io
  - exp.infrastructure.cluster.x-k8s.io
  - addons.cluster.x-k8s.io
  - exp.cluster.x-k8s.io
  - cluster.x-k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - hypershift.openshift.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - "*"
