apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capi-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capi-provider
subjects:
- kind: ServiceAccount
  name: capi-provider
