apiVersion: v1
kind: Service
metadata:
  name: ignition-server
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9090
  selector:
    app: ignition-server
  type: ClusterIP
