apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: control-plane-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: control-plane-operator
        name: control-plane-operator
    spec:
      containers:
      - args:
        - run
        - --namespace
        - $(MY_NAMESPACE)
        - --deployment-name
        - control-plane-operator
        - --metrics-addr
        - 0.0.0.0:8080
        command:
        - /usr/bin/control-plane-operator
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: control-plane-operator
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 6060
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        name: control-plane-operator
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 6060
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 10m
            memory: 80Mi
        volumeMounts:
        - mountPath: /etc/pki/ca-trust/extracted/pem
          name: openshift-config-managed-trusted-ca-bundle
          readOnly: true
      imagePullSecrets:
      - name: pull-secret
      serviceAccount: control-plane-operator
      serviceAccountName: control-plane-operator
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: ca-bundle.crt
            path: tls-ca-bundle.pem
          name: openshift-config-managed-trusted-ca-bundle
          optional: true
        name: openshift-config-managed-trusted-ca-bundle
