apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: controlplane-operator
spec:
  namespaceSelector:
    matchNames:
    - HCP_NAMESPACE
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      name: control-plane-operator
