name: make-verify
on:
  pull_request:
    branches:
      - main
jobs:
  make-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5.3.0
        with:
          go-version-file: go.mod
          cache: false
      - name: Run make verify
        run: make verify
