name: sync cpo container files
on:
  pull_request:
    branches:
      - main
jobs:
  sync-container-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5.3.0
        with:
          go-version-file: go.mod
          cache: false
      - name: Ensure container files in sync
        run: ./hack/tools/git-hooks/cpo-containerfiles-in-sync.sh ./Containerfile.control-plane ./Dockerfile.control-plane
